# Generated by Django 3.2.9 on 2022-01-10 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0005_auto_20220110_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='image',
            field=models.ImageField(blank=True, default='biz_pic/pexels-brett-sayles-1374552.jpg', upload_to='biz_pic/'),
        ),
        migrations.AlterField(
            model_name='facilities',
            name='image',
            field=models.ImageField(blank=True, default='facilities/pexels-pixabay-263402.jpg', upload_to='facilities'),
        ),
        migrations.AlterField(
            model_name='hood',
            name='image',
            field=models.ImageField(blank=True, default='hood_photo/lavington.jpg', upload_to='hood_photo'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='profile_photo/icons8-user-24.png', upload_to='profile_photo'),
        ),
    ]
